### ISSUE TITLE
CODE_OF_CONDUCT and LICENSE not on the list of files to be translated

### ISSUE THREAD

**Issue by SantosSi** [publiccodenet/community-translations-standard#24]
From the files linked in https://standard.publiccode.net/, CODE_OF_CONDUCT and LICENSE are not listed in https://github.com/publiccodenet/community-translations-standard/blob/main/README.md to be translated. Is that a mistake or by intention?
If a mistake, besides the obvious correction of the above README.md, how do we update the translators and the translations (e.g. my [scripts in the PR 23](https://github.com/publiccodenet/community-translations-standard/pull/23) do not include them), and what has to be corrected in the workflow?
If by intention, what is the reason?
(BTW, when opening this Issue, as it is the first one for this project, I was reminded to review the code of conduct.)

**Comment by Ainali** [comment]
I think we excluded them because since we use a standardized code of conduct and license which have their own translations, it would be better to translate 'upstream'. But we forgot to mention that and how to include the translations from there. We should fix that. Also note that from the next release it is [likely that we will switch to our own code of conduct](https://github.com/publiccodenet/standard/pull/643) and then it will have to be included here.

**Comment by SantosSi** [comment]
The hyperlinks to both files are swapped!

**Comment by Ainali** [comment]
> The hyperlinks to both files are swapped!

Where are they swapped?

**Comment by SantosSi** [comment]
Code of conduct links to CONTRIBUTING and vice versa:
```
- [CODE_OF_CONDUCT.md](https://github.com/publiccodenet/standard/blob/main/CONTRIBUTING.md)
- [CONTRIBUTING.md](https://github.com/publiccodenet/standard/blob/main/CODE_OF_CONDUCT.md)
```

**Comment by Ainali** [comment]
Ah, I see, good catch! I created #26 to fix it.

**Comment by ericherman** [comment]
Thanks @SantosSi !
